pipeline {
    agent {
        kubernetes {
            yamlFile 'podTemplate.yaml'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/your-username/sample-app.git'
            }
        }

        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Deploy') {
            steps {
                container('kubectl') {
                    sh 'kubectl get pods'
                }
            }
        }
    }
}