apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent

spec:
  containers:
    - name: maven
      image: maven:3.9.6-eclipse-temurin-17
      command:
        - cat
      tty: true

    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true